
image: node:lts
stages:
  - deploy
deploy:
  stage: deploy
  script:
    - echo "@united-codes:registry=https://${CI_SERVER_HOST}/api/v4/packages/npm/">.npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/packages/npm/:_authToken=${FA_TOKEN}">>.npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${FA_TOKEN}">>.npmrc
    - echo "Created the following .npmrc:"; cat .npmrc
    - npm publish --verbose
